server.servlet.context-path=/dataset-dashboard

jopa.ddo.repositoryUrl=https://onto.fel.cvut.cz/rdf4j-server/repositories/ddo-metadata-noinfer
jopa.ddo.repositoryUsername=
jopa.ddo.repositoryPassword=
jopa.ddo.cache_enabled=true

rdf4jServerForDescriptors=https://onto.fel.cvut.cz/rdf4j-server

spipes.service=https://kbss.felk.cvut.cz/sempipes-gacr-dev/service
#spipes.service.wdrDefsFileUrl=file:///opt/projects/16gacr/wdr/src/worldlod.wdr-definitions.baseline.for-8-datasets.2018-05-14.ttl
spipes.service.wdrDefsFileUrl=file:///opt/projects/16gacr/wdr/src/worldlod.wdr-definitions.baseline.8-datasets.ttl
spipes.service.wdrFileUrl=file:///opt/projects/16gacr/wdr/src/worldlod.wdr.ttl